### ISSUE TITLE
Configurations on Define Shared Parameter component

### ISSUE THREAD

**Issue by eirannejad** [mcneel/rhino.inside-revit#354] opened 2020-11-24 20:28 UTC
The component needs inputs to allow configuring shared parameter grouping, parameter data type, parameter discipline and ui grouping, and finally the list of categories for the parameter to bind into.

## RE:
- https://discourse.mcneel.com/t/defining-and-managing-shared-project-parameters/113065

**Comment by kike-garbo** [comment] 2021-07-20 18:35
Duplicate of #107

**Closed by kike-garbo** 2021-07-20 18:35 UTC
Labels: enhancement, new-gh-node
