### ISSUE TITLE
Wall by Profile does not follow profile edges

### ISSUE THREAD

**Issue by scotttd** [mcneel/rhino.inside-revit#338] opened 2020-11-02 21:55 UTC
**Describe the bug**
If corner of this profile is drug around, there is always a Wall, but it never matches the profile shape.

**To Reproduce**
1. Use the existing profile to create a wall by profile.
2. Drag the top right point around to generate lots of wall shapes, but non match the profile itself.

**Expected behavior**
A Wall that matches the profile curve.

**Screenshots**
![image](https://user-images.githubusercontent.com/887876/97923352-b1878e80-1d12-11eb-9097-068832c16624.png)

**Comment by kike-garbo** [comment] 2020-11-04 15:21
I'm unable to reproduce this.

![H6YIbkSXwf](https://user-images.githubusercontent.com/3530512/98129705-ba669480-1eb9-11eb-91bd-24a999723514.gif)

**Comment by kike-garbo** [comment] 2021-08-13 14:34
@scotttd Please test again with the 1.1 and close this issue if fixed.

**Closed** 2021-09-07 17:04 UTC
Labels: bug
