### ISSUE TITLE
Rhino 8 casting view to preview not generating image

### ISSUE THREAD

**Issue by japhyw** [mcneel/rhino.inside-revit#1022] opened 2023-10-02 16:27 UTC
Reported on Discourse

Tested in Revit 2024.1, Rhino 8.0.23272.03001

**https://discourse.mcneel.com/t/bake-title-block-geometry/166114/9?u=japhy**

**Comment by kike-garbo** [comment] 2024-03-19 17:05
It's a duplicate of #1087

**Closed as completed by kike-garbo** 2024-03-19 17:05 UTC
Labels: user-bug, rhino
